kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64 
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-linux-amd64
- name: ara
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ara
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64
    context: ara
    dockerfile: ara/Dockerfile
- name: oauth2-proxy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/oauth2-proxy
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64
    context: oauth2-proxy
    dockerfile: oauth2-proxy/Dockerfile
    build_args:
      - ARCH=amd64
- name: ansible-deploy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ansible-deploy
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64
    context: ansible-deploy
    dockerfile: ansible-deploy/Dockerfile
- name: nginx-exporter
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/nginx-exporter
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64
    context: nginx-exporter
    dockerfile: nginx-exporter/Dockerfile
- name: configmapsecrets
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/configmapsecrets-controller
    tags:
    - latest-amd64
    - ${DRONE_COMMIT_SHA:0:8}-amd64
    context: configmapsecrets
    dockerfile: configmapsecrets/Dockerfile

trigger:
  branch:
    - master

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-arm64
- name: ara
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ara
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: ara
    dockerfile: ara/Dockerfile
- name: oauth2-proxy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/oauth2-proxy
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: oauth2-proxy
    dockerfile: oauth2-proxy/Dockerfile
    build_args:
      - ARCH=arm64
- name: ansible-deploy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ansible-deploy
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: ansible-deploy
    dockerfile: ansible-deploy/Dockerfile
- name: nginx-exporter
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/nginx-exporter
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: nginx-exporter
    dockerfile: nginx-exporter/Dockerfile
- name: configmapsecrets
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/configmapsecrets-controller
    tags:
    - latest-arm64
    - ${DRONE_COMMIT_SHA:0:8}-arm64
    context: configmapsecrets
    dockerfile: configmapsecrets/Dockerfile

trigger:
  branch:
    - master

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-arm
- name: ara
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ara
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: ara
    dockerfile: ara/Dockerfile
- name: oauth2-proxy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/oauth2-proxy
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: oauth2-proxy
    dockerfile: oauth2-proxy/Dockerfile
    build_args:
      - ARCH=armv6
- name: ansible-deploy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ansible-deploy
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: ansible-deploy
    dockerfile: ansible-deploy/Dockerfile
- name: nginx-exporter
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/nginx-exporter
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: nginx-exporter
    dockerfile: nginx-exporter/Dockerfile
- name: configmapsecrets
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/configmapsecrets-controller
    tags:
    - latest-arm
    - ${DRONE_COMMIT_SHA:0:8}-arm
    context: configmapsecrets
    dockerfile: configmapsecrets/Dockerfile

trigger:
  branch:
    - master

---
kind: pipeline
name: manifests

steps:
- name: restic-mysql-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/restic-mysql:latest
    template: quay.io/paulfantom/restic-mysql:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: restic-mysql-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/restic-mysql:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/restic-mysql:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: rsync-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/rsync:latest
    template: quay.io/paulfantom/rsync:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: rsync-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/rsync:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/rsync:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: coredns-ads-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/coredns-ads:latest
    template: quay.io/paulfantom/coredns-ads:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: coredns-ads-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/coredns-ads:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/coredns-ads:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: ara-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/ara:latest
    template: quay.io/paulfantom/ara:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: ara-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/ara:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/ara:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: oauth2-proxy-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/oauth2-proxy:latest
    template: quay.io/paulfantom/oauth2-proxy:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: oauth2-proxy-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/oauth2-proxy:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/oauth2-proxy:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: ansible-deploy-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/ansible-deploy:latest
    template: quay.io/paulfantom/ansible-deploy:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: ansible-deploy-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/ansible-deploy:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/ansible-deploy:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: nginx-exporter-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/nginx-exporter:latest
    template: quay.io/paulfantom/nginx-exporter:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: nginx-exporter-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/nginx-exporter:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/nginx-exporter:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: configmapsecrets-latest
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/configmapsecrets-controller:latest
    template: quay.io/paulfantom/configmapsecrets-controller:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: configmapsecrets-commit
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/configmapsecrets-controller:${DRONE_COMMIT_SHA:0:8}
    template: quay.io/paulfantom/configmapsecrets-controller:${DRONE_COMMIT_SHA:0:8}-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm

trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - amd64
  - arm64
  - arm
