kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: restic-mysql
  image: plugins/docker
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-amd64
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-amd64
    dockerfile: rsync/Dockerfile

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: restic-mysql
  image: plugins/docker
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-arm64
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-arm64
    dockerfile: rsync/Dockerfile

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: restic-mysql
  image: plugins/docker
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-arm
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-arm
    dockerfile: rsync/Dockerfile

---
kind: pipeline
name: manifests

steps:
- name: restic-mysql
  image: plugins/manifest
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/restic-mysql:latest
    template: quay.io/paulfantom/restic-mysql:latest-ARCH
  platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm
- name: rsync
  image: plugins/manifest
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/rsync:latest
    template: quay.io/paulfantom/rsync:latest-ARCH
  platforms:
    - linux/amd64
    - linux/arm64
    - linux/arm

depends_on:
  - amd64
  - arm64
  - arm
