kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    # dry_run: "${DRONE_PULL_REQUEST=0}"
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-amd64
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-amd64
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags: latest-amd64
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-linux-amd64
- name: ara
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ara
    tags: latest-amd64
    context: ara
    dockerfile: ara/Dockerfile
- name: oauth2-proxy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/oauth2-proxy
    tags: latest-amd64
    context: oauth2-proxy
    dockerfile: oauth2-proxy/Dockerfile
    build_args:
      - ARCH=amd64
- name: ansible
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ansible
    tags: latest-amd64
    context: ansible
    dockerfile: ansible/Dockerfile
- name: configmapsecrets
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/configmapsecrets-controller
    tags: latest-amd64
    context: configmapsecrets
    dockerfile: configmapsecrets/Dockerfile


trigger:
  branch:
    - master

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-arm64
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-arm64
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags: latest-arm64
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-arm64
- name: ara
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ara
    tags: latest-arm64
    context: ara
    dockerfile: ara/Dockerfile
- name: oauth2-proxy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/oauth2-proxy
    tags: latest-arm64
    context: oauth2-proxy
    dockerfile: oauth2-proxy/Dockerfile
    build_args:
      - ARCH=arm64
- name: ansible
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ansible
    tags: latest-arm64
    context: ansible
    dockerfile: ansible/Dockerfile
- name: configmapsecrets
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/configmapsecrets-controller
    tags: latest-arm64
    context: configmapsecrets
    dockerfile: configmapsecrets/Dockerfile


trigger:
  branch:
    - master

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-arm
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-arm
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags: latest-arm
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-arm
- name: ara
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ara
    tags: latest-arm
    context: ara
    dockerfile: ara/Dockerfile
- name: oauth2-proxy
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/oauth2-proxy
    tags: latest-arm
    context: oauth2-proxy
    dockerfile: oauth2-proxy/Dockerfile
    build_args:
      - ARCH=armv6
- name: ansible
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/ansible
    tags: latest-arm
    context: ansible
    dockerfile: ansible/Dockerfile
- name: configmapsecrets
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/configmapsecrets-controller
    tags: latest-arm
    context: configmapsecrets
    dockerfile: configmapsecrets/Dockerfile


trigger:
  branch:
    - master

---
kind: pipeline
name: manifests

steps:
- name: restic-mysql
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/restic-mysql:latest
    template: quay.io/paulfantom/restic-mysql:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: rsync
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/rsync:latest
    template: quay.io/paulfantom/rsync:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: coredns-ads
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/coredns-ads:latest
    template: quay.io/paulfantom/coredns-ads:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: ara
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/ara:latest
    template: quay.io/paulfantom/ara:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: oauth2-proxy
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/oauth2-proxy:latest
    template: quay.io/paulfantom/oauth2-proxy:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: ansible
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/ansible:latest
    template: quay.io/paulfantom/ansible:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: configmapsecrets
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/configmapsecrets-controller:latest
    template: quay.io/paulfantom/configmapsecrets-controller:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm


trigger:
  branch:
    - master
  event:
    - push

depends_on:
  - amd64
  - arm64
  - arm
