kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-amd64
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-amd64
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags: latest-amd64
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-linux-amd64

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-arm64
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-arm64
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags: latest-arm64
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-arm64

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: restic-mysql
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/restic-mysql
    tags: latest-arm
    context: restic-mysql
    dockerfile: restic-mysql/Dockerfile
- name: rsync
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/rsync
    tags: latest-arm
    context: rsync
    dockerfile: rsync/Dockerfile
- name: coredns-ads
  image: plugins/docker
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    registry: quay.io
    repo: quay.io/paulfantom/coredns-ads
    tags: latest-arm
    context: coredns-ads
    dockerfile: coredns-ads/Dockerfile
    build_args:
      - FILE=coredns-ads-arm

---
kind: pipeline
name: manifests

steps:
- name: restic-mysql
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/restic-mysql:latest
    template: quay.io/paulfantom/restic-mysql:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: rsync
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/rsync:latest
    template: quay.io/paulfantom/rsync:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
- name: coredns-ads
  image: plugins/manifest
  depends_on: [clone]
  settings:
    username:
      from_secret: QUAY_USERNAME
    password:
      from_secret: QUAY_PASSWORD
    target: quay.io/paulfantom/coredns-ads:latest
    template: quay.io/paulfantom/coredns-ads:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm

depends_on:
  - amd64
  - arm64
  - arm
