---
name: "versions update"

on:
  workflow_dispatch:
  schedule:
  - cron: '13 12 * * *'

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update versions
        run: ./versions.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[bot] Automated version update"
          title: "[bot] Automated version update"
          body: |
            This is an automated version update performed from CI on behalf of @paulfantom.
            Configuration of the workflow is located in `.github/workflows/versions.yml`
          assignees: paulfantom
          labels: enhancement
          branch: automated-updates
          delete-branch: true
          token: ${{ secrets.PAT_SECRET }}
